//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleModel_Stat
    {
        public int SingleModelId { get; set; }
        public short Value { get; set; }
        public int StatId { get; set; }
    
        public virtual Stat Stat { get; set; }
    }
}
